// <auto-generated />
using System;
using Backend_Rider.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_Rider.Migrations
{
    [DbContext(typeof(SydlinkDbContext))]
    [Migration("20260930075148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_Rider.Models.Besked", b =>
                {
                    b.Property<int>("BeskedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeskedId"));

                    b.Property<string>("Beskeden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<int?>("MedarbejderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime2");

                    b.Property<int>("SagId")
                        .HasColumnType("int");

                    b.Property<int>("SagsNummer")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeskedId");

                    b.HasIndex("KundeId");

                    b.HasIndex("MedarbejderId");

                    b.HasIndex("SagId");

                    b.ToTable("Beskeder");
                });

            modelBuilder.Entity("Backend_Rider.Models.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kodeord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundeId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Backend_Rider.Models.Medarbejder", b =>
                {
                    b.Property<int>("MedarbejderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedarbejderId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kodeord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedarbejderId");

                    b.ToTable("Medarbejdere");
                });

            modelBuilder.Entity("Backend_Rider.Models.Sag", b =>
                {
                    b.Property<int>("SagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SagId"));

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int?>("MedarbejderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Oprettet")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioritet")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SagId");

                    b.HasIndex("KundeId");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Sager");
                });

            modelBuilder.Entity("Backend_Rider.Models.Besked", b =>
                {
                    b.HasOne("Backend_Rider.Models.Kunde", "Kunde")
                        .WithMany("Beskeder")
                        .HasForeignKey("KundeId");

                    b.HasOne("Backend_Rider.Models.Medarbejder", "Medarbejder")
                        .WithMany("Beskeder")
                        .HasForeignKey("MedarbejderId");

                    b.HasOne("Backend_Rider.Models.Sag", "sag")
                        .WithMany("beskeder")
                        .HasForeignKey("SagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kunde");

                    b.Navigation("Medarbejder");

                    b.Navigation("sag");
                });

            modelBuilder.Entity("Backend_Rider.Models.Sag", b =>
                {
                    b.HasOne("Backend_Rider.Models.Kunde", "Kunde")
                        .WithMany("Sager")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Rider.Models.Medarbejder", "Medarbejder")
                        .WithMany("Sager")
                        .HasForeignKey("MedarbejderId");

                    b.Navigation("Kunde");

                    b.Navigation("Medarbejder");
                });

            modelBuilder.Entity("Backend_Rider.Models.Kunde", b =>
                {
                    b.Navigation("Beskeder");

                    b.Navigation("Sager");
                });

            modelBuilder.Entity("Backend_Rider.Models.Medarbejder", b =>
                {
                    b.Navigation("Beskeder");

                    b.Navigation("Sager");
                });

            modelBuilder.Entity("Backend_Rider.Models.Sag", b =>
                {
                    b.Navigation("beskeder");
                });
#pragma warning restore 612, 618
        }
    }
}
